import type { Metadata } from "next";
import { Geist_Mono, Manrope } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { CRM_THEME_STORAGE_KEY } from "@/lib/theme";
import { GlobalNotifierProvider } from "./Components/Shared/GlobalNotifier";
import { ActiveModuleProvider } from "./Components/Shared/ActiveModuleContext";
import ModuleHubHost from "./Components/Shared/ModuleHubHost";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeBootstrap = `
(function () {
  try {
    var stored = localStorage.getItem(${JSON.stringify(CRM_THEME_STORAGE_KEY)});
    var theme = stored === "dark" || stored === "light" ? stored : "light";
    document.documentElement.classList.remove("light", "dark");
    document.documentElement.classList.add(theme);
    document.documentElement.style.colorScheme = theme;
  } catch (error) {}
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={manrope.variable} suppressHydrationWarning>
      <body
        className={`${manrope.className} ${geistMono.variable} font-sans antialiased`}
      >
        <Script id="crm-theme-bootstrap" strategy="beforeInteractive">
          {themeBootstrap}
        </Script>
        <GlobalNotifierProvider>
          <ActiveModuleProvider>
            <ModuleHubHost />
            {children}
          </ActiveModuleProvider>
        </GlobalNotifierProvider>
      </body>
    </html>
  );
}
